A19 tasks are implemented
rajeevramanTMM/PSI pull request #4
Opened 2023-04-21 08:36 UTC by rajeevramanTMM

2023-04-23 02:54 UTC, tarydon requested changes

2023-04-23 02:54 UTC, tarydon commented on Parser/Node.cs
> +}
Change this to:
`public record NIfStmt (NExpr Condition, NStmt IfPart, NStmt? ElsePart)`

2023-04-23 02:54 UTC, tarydon commented on Parser/Node.cs
> +}
The body of a while loop is a _single_ statement. Even if there are multiple operations to complete, it is still a single CompoundStmt. 
`public record NWhileStmt (NExpr Condition, NStmt Body)`

2023-04-23 02:54 UTC, tarydon commented on Parser/Parser.cs
> +      Expect (DO, "Expecting do statement");
It's just a **DO** keyword not a **do statement**

2023-04-24 16:22 UTC, rajeevramanTMM commented
Review changes applied

2023-04-30 10:51 UTC, closed without merging